# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-14 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170114_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='data',
            new_name='jdata',
        ),
    ]
